### ISSUE TITLE
Add auto beautify on save

### ISSUE THREAD

**Issue by piotrraczynski** [vingorius/jade-beautify#1]
Please add settings pane  and auto beautify on save setting. This is useful, especially when you work in a team and someone forgets to beautify a file.

**Comment by vingorius** [comment]
OK @piotrraczynski , I'll check.

**Comment by vingorius** [comment]
@piotrraczynski , i checked what you request, but i don't know how, so fork it if you can.

**Comment by jerone** [comment]
Atom Beautify does this: https://github.com/Glavin001/atom-beautify/blob/288b3813bc2bb4f3f7426ae4daa5593b54e52261/src/beautify.coffee#L411

**Comment by vingorius** [comment]
Thanks @jerone , i'll check.
