### ISSUE TITLE
Doesn't work with window:save-all

### ISSUE THREAD

**Issue by jerone** [vingorius/jade-beautify#4]
When editing multiple documents and then pressing Save All (command `window:save-all`) this package doesn't seems to execute, while normal Save (command `core:save`) does work.

**Comment by vingorius** [comment]
sorry for late, i'll check.

**Comment by vingorius** [comment]
To: @jerone

When save-all, do i check a jade-file changed or not?
Even when a jade file is not changed, do i beautify it?

**Comment by jerone** [comment]
Good question! I wouldn't mind if you save unchanged files, but I know other people who use filewatchers for for example Grunt might have issues with that. I would check how [atom-beautify](https://github.com/Glavin001/atom-beautify) does it.

**Comment by vingorius** [comment]
How about give new config option "Beautify on save-all", Even the jade file is not modified, I is enforced to beautify. Waiting your opinion.

**Comment by vingorius** [comment]
@jerone  Any update?

**Comment by jerone** [comment]
@vingorius Sorry must have missed your reply. 

Apparently [people don't like it](https://github.com/atom/atom/issues/2871) when non-modified files are saved.

I would just implement the save-all feature (for modified files only), because when I save it I expect it to be beautified and compiled too. Maybe adding a default enabled option would help others.

Does this help you?
