### ISSUE TITLE
Publish as package to npm for reusability

### ISSUE THREAD

**Issue by Glavin001** [vingorius/jade-beautify#7]
If you publish this package I can add support for it on Atom Beautify. See https://github.com/Glavin001/atom-beautify/issues/199
Thank you and great work!

**Comment by vingorius** [comment]
Good morning @Glavin001. I did read the article "How to add a Beautifier for a Language" a couple month ago. i forked your atom-beautify for adding jade support. and i tried. but as a newbie, it was too diffcult to do. With my whole heart, i want to contribute community if i can. but it will take many time to find out how atom-beautify work and to run coffeescript. If there are a short way to help you, tell me. tks.

**Comment by Glavin001** [comment]
Don't worry about that Atom Beautify integration -- I will take care of that for you :smiley: . If you could publish a package that implemented jade beautification then I will make the appropriate changes to Atom Beautify.

Suggested usage for jade beautify package:

``` javascript
var jadeBeautify = require('jade-beautify');
var code = "...";
var options = {
  indent_size: 4
};
try {
  var output = jadeBeautify(code, options);
} catch (error) {
  // Error occurred
}
```

Great work so far. Thanks in advance!

**Comment by vingorius** [comment]
Ok @Glavin001. Did you mean that i write a new npm package for atom-beautify. if yes, i will. and how about changing it's name to 'beautify-jade' without confusing.

**Comment by Glavin001** [comment]
> Did you mean that i write a new npm package for atom-beautify. 

Yes, to publish to npm, (see https://docs.npmjs.com/getting-started/publishing-npm-packages for details) however not necessarily specifically for Atom Beautify.
By publishing to npm it will allow other developers to access your package as well. Maybe a Sublime package will use it, etc.
The important part is that it is modular, does not depend on Atom at all. It is just a simple, Node.js package published to npm.

> how about changing it's name to 'beautify-jade' without confusing.

Atom packages are published with apm while Node.js packages are published to npm.
I do not see an existing package named `jade-beautify` published to npm yet. See https://www.npmjs.com/search?q=jade-beautify

So please feel free to keep the the name as `jade-beautify`.

Thank you.

**Comment by vingorius** [comment]
Ok. i understand you clearly. but is it possible that a module support both a npm node moudle and a atom package simultaniously ? there's only one entry-porint 'main' on 'package.json' file.

**Comment by Glavin001** [comment]
It would probably be easiest if you created a separate package to publish to npm.

**Comment by vingorius** [comment]
That's what i say it making confusing.
Avoid name conflicting on github, how about change library package name to 'jade-beautifier'?

**Comment by vingorius** [comment]
And FYI, Jade change it's project name to 'Pug'.

https://github.com/pugjs/jade/issues/2184

**Comment by Glavin001** [comment]
Good eye! I did not know that. Thanks for sharing.
So I suppose pug-beautify makes sense and afterwards I will add pug support to Atom Beautify.

**Comment by vingorius** [comment]
Good Morning @Glavin001 . I'm very happy to release [a pug-beautify on npm](https://www.npmjs.com/package/pug-beautify). First i modified the jade-beautify for monitoring whether there's error. Check that module what you want. Enjoy it. Thanks.
