### ISSUE TITLE
Add support for visual studio code

### ISSUE THREAD

**Issue by vadim82** [vingorius/jade-beautify#9]
Can you please add support to vscode so that we can type alt-shift-f to beautify jade code. Currently there are no good plugins to do this.

**Comment by vingorius** [comment]
@vadim82 ,I've never used vscode yet. someone else may help this.

**Comment by mrmlnc** [comment]
I'll start working on this issue today.

**Comment by mrmlnc** [comment]
@vadim82,

As I understand it, this package can only change the indentation of code and omit div tags? 

Are you sure that this extension is needed in the VS Code? In VS Code you can use standard tools to change indent of code.

![2016-09-22_19-27-19](https://cloud.githubusercontent.com/assets/7034281/18756974/9a9a8f0a-80fa-11e6-89e2-fc989871aefe.gif)

**Comment by mrmlnc** [comment]
Done. See https://goo.gl/VLj9SL

**Comment by vingorius** [comment]
Tks @mrmlnc .
